apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: 8919687630/springboot-postgres
        env:
          - name: POSTGRES_HOST
            value: "10.100.90.240"
          - name: POSTGRES_USER
            value: "techcoms"
          - name: POSTGRES_PASSWORD
            value: "techcoms@123"  
        ports:
          - containerPort: 33333

